### ISSUE TITLE
Feature is broken in Spotify circa March 2022

### ISSUE THREAD

**Issue by wmichelin** [abdulazizali77/sloooop#62]
Widget renders offscreen at the top left and is not responsive

<img width="274" alt="image" src="https://user-images.githubusercontent.com/5488896/159822389-4840b60c-beee-428e-8816-ef818028a484.png">

**Comment by abdulazizali77** [comment]
@wmichelin thanks for reporting! havent looked at this in a while, i will investigate soonish!

**Comment by abdulazizali77** [comment]
looks like Spotify changed the `class="progress-bar__bg"` to `data-testid="progress-bar-background"`

**Comment by abdulazizali77** [comment]
The fix should do it, but will take a while to resubmit to chrome store. Additionally will probably need to update to manifest v3 #63 before the update is accepted..

**Comment by abdulazizali77** [comment]
@wmichelin works on my end, but as noted not republished yet
